### ISSUE TITLE
MilSci Bug Report

### ISSUE THREAD

**Issue by MilSci** [N0tMyFaultOG/Fawe-1.13#1]
# Bug report
- `//removenear <item> 0` -> https://gist.github.com/N0tMyFaultOG/b761ccbbf6f89bccab09fe5e40cce18c
- //snow doesn't seem to work

**Comment by MilSci** [comment]
Can't rotate any 1.13 block it seems //set stone_brick_stairs:1 works but not //set block:# with 1.13 blocks

**Comment by N0tMyFaultOG** [comment]
Issues above fixed, not pulled yet
